/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TreeCrackinPOS;

class AppTest {
//    @Test void appHasAGreeting() {
//        KernelPrototype classUnderTest = new KernelPrototype();
//        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
//    }
}
